version: '3.6'

volumes:
  dados-eleicao:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    security_opt:
      - label:disable
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    ports:
        - 8000:80
    security_opt:
      - label:disable
    volumes:
        - dados-eleicao:/usr/share/nginx/html/dados/
        - ${APP_CODE_PATH_HOST}/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ${APP_CODE_PATH_HOST}/nginx/nginx.conf:/etc/nginx/nginx.conf

  client:
    build:
      context: ./client
    env_file: .env
    depends_on:
      - airflow
      - redis
      - nginx
    security_opt:
      - label:disable
    volumes:
      - dados-eleicao:/tmp/nginx/
    networks:
      - backend

  redis:
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION:-5}
    restart: unless-stopped
    security_opt:
      - label:disable
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT:-6379}:6379/tcp"
    networks:
      backend:
        aliases:
          - redisserver

  airflow:
    image: apache/airflow
    entrypoint: ["./start.sh"]
    security_opt:
      - label:disable
    volumes:
      - ${DATA_PATH_HOST}/airflow:/opt/airflow:Z
      - ${APP_CODE_PATH_HOST}/airflow/dags:/opt/airflow/dags
      - ${APP_CODE_PATH_HOST}/airflow/start.sh:/opt/airflow/start.sh
      - ${APP_CODE_PATH_HOST}/airflow/requirements.txt:/opt/airflow/requirements.txt
      
    depends_on:
      - redis
      - postgres
    ports:
      - "${AIRFLOW_PORT:-8081}:8080/tcp"
    networks:
      - backend
