version: '3.6'

volumes:
  html-volume:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
    ports:
        - 80:80
    volumes:
        - html-volume:/usr/share/nginx/html/

  client:
    build:
      context: ./client
    env_file: .env
    depends_on:
      - airflow
      - redis
      - nginx
    volumes:
      - html-volume:/tmp/nginx/
    networks:
      - backend

  redis:
    build:
      context: ./redis
      args:
        - REDIS_VERSION=${REDIS_VERSION:-5}
    restart: unless-stopped
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT:-6379}:6379/tcp"
    networks:
      backend:
        aliases:
          - redisserver

  airflow:
    image: apache/airflow
    entrypoint: ["./start.sh"]
    volumes:
      - ${APP_CODE_PATH_HOST}/airflow/start.sh:/opt/airflow/start.sh
      - ${APP_CODE_PATH_HOST}/airflow/requirements.txt:/opt/airflow/requirements.txt
      - ${APP_CODE_PATH_HOST}/airflow/dags:/opt/airflow/dags
      - /usr/bin/docker:/usr/bin/docker:z
      - /var/run/docker.sock:/var/run/docker.sock:z
    depends_on:
      - redis
    ports:
      - "${AIRFLOW_PORT:-8081}:8080/tcp"
    networks:
      - backend
